# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  builder: html
  fail_on_warning: false
  # configuration: conf.py

# Additional formats
# formats:
#   - pdf
#   - htmlzip
#   - epub

python:
  version: 3.8
  install:
    - requirements: requirements.txt

build:
  image: latest
