name: __all__
on: push

jobs:
  all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sphinx-build -a -E -j auto --color -b doctest . /tmp/
      - run: find . -path '*assignments*' -name '*.py' \
                    -not -path "./advanced/*" \
                    -not -path "./design-patterns/*" \
                    -not -path "./django/*" \
                    -not -path "./machine-learning/*" \
                    -not -path "./matplotlib/*" \
                    -not -path "./network/*" \
                    -print -exec python -m doctest '{}' \;

  basics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: sphinx-build -a -E -j auto --color -b doctest basics /tmp/
      - run: find basics -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' \;

  intermediate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: sphinx-build -a -E -j auto --color -b doctest stdlib /tmp/
      - run: find stdlib -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' \;

  advanced:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: sphinx-build -a -E -j auto --color -b doctest advanced /tmp/
      - run: find advanced -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' \;

  design-patterns:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: sphinx-build -a -E -j auto --color -b doctest design-patterns /tmp/
      - run: find design-patterns -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' \;
