name: Doctests
on: push

jobs:
  doctest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout the Code from GIT Repository
      uses: actions/checkout@v2

    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.4'

    - name: Setup PIP Cache
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Doctest Listings
      run: sphinx-build -a -E -j auto --color -b doctest . /tmp/

    - name: About
      run: |
        sphinx-build -a -E -j auto --color -b doctest about /tmp/
        find about -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Advanced
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest advanced /tmp/
    #    find advanced -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: Basics
      run: |
        sphinx-build -a -E -j auto --color -b doctest basics /tmp/
        find basics -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: Data Science
      run: |
        sphinx-build -a -E -j auto --color -b doctest data-science /tmp/
        find data-science -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Design Patterns
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest design-patterns /tmp/
    #    find design-patterns -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: DevOps
      run: |
        sphinx-build -a -E -j auto --color -b doctest devops /tmp/
        find devops -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Django
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest django /tmp/
    #    find django -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Dragon
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest dragon /tmp/
    #    find dragon -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: FastAPI
      run: |
        sphinx-build -a -E -j auto --color -b doctest fastapi /tmp/
        find fastapi -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Machine Learning
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest machine-learning /tmp/
    #    find machine-learning -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Matplotlib
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest matplotlib /tmp/
    #    find matplotlib -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    # - name: Network
    #  run: |
    #    sphinx-build -a -E -j auto --color -b doctest network /tmp/
    #    find network -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: NumPy
      run: |
        sphinx-build -a -E -j auto --color -b doctest numpy /tmp/
        find numpy -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: OOP
      run: |
        sphinx-build -a -E -j auto --color -b doctest oop /tmp/
        find oop -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: Pandas
      run: |
        sphinx-build -a -E -j auto --color -b doctest pandas /tmp/
        find pandas -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

    - name: Stdlib
      run: |
        sphinx-build -a -E -j auto --color -b doctest stdlib /tmp/
        find stdlib -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;
