name: __all__
on: push

jobs:
  __all__:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout the Code from GIT Repository
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'

      - name: Setup PIP Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Upgrade PIP
        run: pip install --upgrade pip

      - name: Doctest About
        run: |
          cd about
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Advanced
        run: |
          cd advanced
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Basics
        run: |
          cd basics
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Data Science
        run: |
          cd data-science
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Design Patterns
        run: |
          cd design-patterns
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest DevOps
        run: |
          cd devops
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Django
        run: |
          cd django
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Dragon
        run: |
          cd dragon
          pip install -r requirements.txt
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest FastAPI
        run: |
          cd fastapi
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Machine Learning
        run: |
          cd machine-learning
          # pip install -r requirements.txt
          # sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Matplotlib
        run: |
          cd matplotlib
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Network
        run: |
          cd network
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          # find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest NumPy
        run: |
          cd numpy
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest OOP
        run: |
          cd oop
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Pandas
        run: |
          cd pandas
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest Stdlib
        run: |
          cd stdlib
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' -exec python -m doctest '{}' \;

      - name: Doctest __all__
        run: |
          pip install -r requirements.txt
          sphinx-build -a -E -j auto --color -b doctest . /tmp/
          find . -path '*assignments*' -name '*.py' \
                 -not -path "./advanced/*" \
                 -not -path "./design-patterns/*" \
                 -not -path "./django/*" \
                 -not -path "./machine-learning/*" \
                 -not -path "./matplotlib/*" \
                 -not -path "./network/*" \
                 -exec python -m doctest '{}' \;
