name: Tests
on: push

jobs:
  setup:
    container: 'python:3.9.4-alpine'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  about:
    needs: setup
    steps:
    - run: sphinx-build -a -E -j auto --color -b doctest about /tmp/
    - run: find about -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +

  advanced:
    needs: setup
    steps:
    - run: sphinx-build -a -E -j auto --color -b doctest advanced /tmp/
    # - run: find advanced -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +

  basics:
    needs: setup
    steps:
    - run: sphinx-build -a -E -j auto --color -b doctest basics /tmp/
    - run: find basics -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    data-science:
#      - needs: setup
#      - run: sphinx-build -a -E -j auto --color -b doctest data-science /tmp/
#      - run: find data-science -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    design-patterns:
#      - needs: setup
#      - run: sphinx-build -a -E -j auto --color -b doctest design-patterns /tmp/
#      - run: find design-patterns -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest Devops Assignments
#      run: find devops -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    #- name: Doctest Django Assignments
#    #  run: find django -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    #- name: Doctest Dragon Assignments
#    #  run: find dragon -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest Fastapi Assignments
#      run: find fastapi -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    #- name: Doctest Machine Learning Assignments
#    #  run: find machine-learning -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    #- name: Doctest Matplotlib Assignments
#    #  run: find matplotlib -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    #- name: Doctest Network Assignments
#    #  run: find network -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest Numpy Assignments
#      run: find numpy -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest OOP Assignments
#      run: find oop -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest Pandas Assignments
#      run: find pandas -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
#
#    - name: Doctest Stdlib Assignments
#      run: find stdlib -path '*assignments*' -name '*.py' -print -exec python -m doctest '{}' +
